name: my_travaly
description: A hotel booking Flutter application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.4
  google_sign_in: ^6.2.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  http: ^1.1.0
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
