// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVbIhL4I9OBtGD4s2-OM5FS_TyCcD0B24',
    appId: '1:307288433655:web:96f8190128e2879f3304f2',
    messagingSenderId: '307288433655',
    projectId: 'my-travaly-bcafe',
    authDomain: 'my-travaly-bcafe.firebaseapp.com',
    storageBucket: 'my-travaly-bcafe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXbT30jaD4bO6RezKAYssCFlw9JM6oycs',
    appId: '1:307288433655:android:9e227146aa1867e03304f2',
    messagingSenderId: '307288433655',
    projectId: 'my-travaly-bcafe',
    storageBucket: 'my-travaly-bcafe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw3tiZh02s_CTALxr4TpcMcm1wZBjvPEY',
    appId: '1:307288433655:ios:fc010d3f87ebf1ae3304f2',
    messagingSenderId: '307288433655',
    projectId: 'my-travaly-bcafe',
    storageBucket: 'my-travaly-bcafe.firebasestorage.app',
    iosBundleId: 'com.example.myTravaly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw3tiZh02s_CTALxr4TpcMcm1wZBjvPEY',
    appId: '1:307288433655:ios:fc010d3f87ebf1ae3304f2',
    messagingSenderId: '307288433655',
    projectId: 'my-travaly-bcafe',
    storageBucket: 'my-travaly-bcafe.firebasestorage.app',
    iosBundleId: 'com.example.myTravaly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVbIhL4I9OBtGD4s2-OM5FS_TyCcD0B24',
    appId: '1:307288433655:web:bc3e303970a5a1003304f2',
    messagingSenderId: '307288433655',
    projectId: 'my-travaly-bcafe',
    authDomain: 'my-travaly-bcafe.firebaseapp.com',
    storageBucket: 'my-travaly-bcafe.firebasestorage.app',
  );
}
